name: 'PHP CodeSniffer'
on:
  pull_request:
    paths:
      - 'classes/**.php'
      - 'includes/**.php'
      - '*.php'
      - 'composer.json'
      - '.github/workflows/php-phpcs.yml'
jobs:
  phpcs:
    uses: pods-framework/.github/.github/workflows/php-phpcs.yml@main
    secrets: inherit
